"""phone should be string

Revision ID: 0bfa275c6555
Revises: 2cf19c01247a
Create Date: 2023-08-05 11:41:47.419382

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0bfa275c6555'
down_revision = '2cf19c01247a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('members', schema=None) as batch_op:
        batch_op.alter_column('phone_number',
               existing_type=mysql.INTEGER(),
               type_=sa.String(length=10),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('members', schema=None) as batch_op:
        batch_op.alter_column('phone_number',
               existing_type=sa.String(length=10),
               type_=mysql.INTEGER(),
               existing_nullable=False)

    # ### end Alembic commands ###
