"""uuid

Revision ID: 216a27ac80e2
Revises: 11b75dad8cb3
Create Date: 2023-08-02 17:48:35.232441

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '216a27ac80e2'
down_revision = '11b75dad8cb3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('detected_individuals', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'detected_media', ['medium'], ['detected_medium_id'])

    with op.batch_alter_table('individuals', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'media', ['medium'], ['medium_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('individuals', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('detected_individuals', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
