"""contributions and actions tables

Revision ID: 2cf19c01247a
Revises: 659ad308bfaa
Create Date: 2023-08-04 13:56:48.664274

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2cf19c01247a'
down_revision = '659ad308bfaa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('actions',
    sa.Column('action_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=15), nullable=True),
    sa.PrimaryKeyConstraint('action_id')
    )
    op.create_table('contributions',
    sa.Column('contribution_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('contributor', sa.Integer(), nullable=True),
    sa.Column('num_files', sa.Integer(), nullable=False),
    sa.Column('action', sa.Integer(), nullable=True),
    sa.Column('time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['action'], ['actions.action_id'], ),
    sa.ForeignKeyConstraint(['contributor'], ['members.member_id'], ),
    sa.PrimaryKeyConstraint('contribution_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('contributions')
    op.drop_table('actions')
    # ### end Alembic commands ###
