"""detecte date -> datetime

Revision ID: 2efc493e2a04
Revises: 325cf0647d66
Create Date: 2023-08-22 23:45:58.047462

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2efc493e2a04'
down_revision = '325cf0647d66'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('schedule_detect', schema=None) as batch_op:
        batch_op.add_column(sa.Column('detect_datetime', sa.Date(), nullable=True))
        batch_op.drop_column('detect_date')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('schedule_detect', schema=None) as batch_op:
        batch_op.add_column(sa.Column('detect_date', sa.DATE(), nullable=True))
        batch_op.drop_column('detect_datetime')

    # ### end Alembic commands ###
