"""uuid as medium id

Revision ID: 2fcb0df64562
Revises: 34b20c1fe95b
Create Date: 2023-08-02 16:32:22.367675

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2fcb0df64562'
down_revision = '34b20c1fe95b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('detected_individuals', schema=None) as batch_op:
        batch_op.drop_constraint('detected_individuals_ibfk_1', type_='foreignkey')

    with op.batch_alter_table('individuals', schema=None) as batch_op:
        batch_op.drop_constraint('individuals_ibfk_1', type_='foreignkey')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('individuals', schema=None) as batch_op:
        batch_op.create_foreign_key('individuals_ibfk_1', 'media', ['medium'], ['medium_id'])

    with op.batch_alter_table('detected_individuals', schema=None) as batch_op:
        batch_op.create_foreign_key('detected_individuals_ibfk_1', 'detected_media', ['medium'], ['detected_medium_id'])

    # ### end Alembic commands ###
