"""uuid as medium id

Revision ID: 324f112dd3d0
Revises: 525cb139fa82
Create Date: 2023-08-02 16:22:27.749310

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '324f112dd3d0'
down_revision = '525cb139fa82'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('detected_individuals', schema=None) as batch_op:
        batch_op.alter_column('pending_individual_id',
               existing_type=mysql.INTEGER(),
               type_=sa.String(length=22),
               existing_nullable=False)

    with op.batch_alter_table('detected_media', schema=None) as batch_op:
        batch_op.alter_column('detected_medium_id',
               existing_type=mysql.INTEGER(),
               type_=sa.String(length=22),
               existing_nullable=False)

    with op.batch_alter_table('individuals', schema=None) as batch_op:
        batch_op.alter_column('individual_id',
               existing_type=mysql.INTEGER(),
               type_=sa.String(length=22),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('individuals', schema=None) as batch_op:
        batch_op.alter_column('individual_id',
               existing_type=sa.String(length=22),
               type_=mysql.INTEGER(),
               existing_nullable=False)

    with op.batch_alter_table('detected_media', schema=None) as batch_op:
        batch_op.alter_column('detected_medium_id',
               existing_type=sa.String(length=22),
               type_=mysql.INTEGER(),
               existing_nullable=False)

    with op.batch_alter_table('detected_individuals', schema=None) as batch_op:
        batch_op.alter_column('pending_individual_id',
               existing_type=sa.String(length=22),
               type_=mysql.INTEGER(),
               existing_nullable=False)

    # ### end Alembic commands ###
