"""empty message

Revision ID: 325cf0647d66
Revises: 9841eb615eaa
Create Date: 2023-08-22 23:41:31.997455

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '325cf0647d66'
down_revision = '9841eb615eaa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('schedule_detect',
    sa.Column('schedule_detect_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('num_files', sa.Integer(), nullable=True),
    sa.Column('detect_date', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('schedule_detect_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('schedule_detect')
    # ### end Alembic commands ###
