"""perch_mount column

Revision ID: 344c7b1e81d3
Revises: a6773bdef653
Create Date: 2023-07-30 23:42:59.447089

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '344c7b1e81d3'
down_revision = 'a6773bdef653'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('perch_mounts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('latest_note', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('is_priority', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('claim_by', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'members', ['claim_by'], ['member_id'])
        batch_op.drop_column('note')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('perch_mounts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('note', mysql.TEXT(), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('claim_by')
        batch_op.drop_column('is_priority')
        batch_op.drop_column('latest_note')

    # ### end Alembic commands ###
