"""uuid as medium id

Revision ID: 34b20c1fe95b
Revises: 489ecfa2140c
Create Date: 2023-08-02 16:30:41.355940

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '34b20c1fe95b'
down_revision = '489ecfa2140c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('detected_individuals', schema=None) as batch_op:
        batch_op.alter_column('medium',
               existing_type=mysql.INTEGER(),
               type_=sa.String(length=22),
               existing_nullable=True)
        batch_op.drop_constraint('detected_individuals_ibfk_1', type_='foreignkey')

    with op.batch_alter_table('individuals', schema=None) as batch_op:
        batch_op.alter_column('medium',
               existing_type=mysql.INTEGER(),
               type_=sa.String(length=22),
               existing_nullable=True)
        batch_op.drop_constraint('individuals_ibfk_1', type_='foreignkey')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('individuals', schema=None) as batch_op:
        batch_op.create_foreign_key('individuals_ibfk_1', 'media', ['medium'], ['medium_id'])
        batch_op.alter_column('medium',
               existing_type=sa.String(length=22),
               type_=mysql.INTEGER(),
               existing_nullable=True)

    with op.batch_alter_table('detected_individuals', schema=None) as batch_op:
        batch_op.create_foreign_key('detected_individuals_ibfk_1', 'detected_media', ['medium'], ['detected_medium_id'])
        batch_op.alter_column('medium',
               existing_type=sa.String(length=22),
               type_=mysql.INTEGER(),
               existing_nullable=True)

    # ### end Alembic commands ###
