"""species usage count

Revision ID: 3571940cbe27
Revises: 968f08666507
Create Date: 2023-08-07 17:24:57.224074

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3571940cbe27'
down_revision = '968f08666507'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('species', schema=None) as batch_op:
        batch_op.add_column(sa.Column('usage_count', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('species', schema=None) as batch_op:
        batch_op.drop_column('usage_count')

    # ### end Alembic commands ###
