"""prey identify by

Revision ID: 3fc523bb75c2
Revises: db723917e205
Create Date: 2023-08-09 15:48:14.483941

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3fc523bb75c2'
down_revision = 'db723917e205'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('individuals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('prey_identify_by', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'members', ['prey_identify_by'], ['member_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('individuals', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('prey_identify_by')

    # ### end Alembic commands ###
