"""uuid as medium id

Revision ID: 3fea6b016d17
Revises: 47897f5c147f
Create Date: 2023-08-02 16:33:56.893364

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3fea6b016d17'
down_revision = '47897f5c147f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('detected_individuals', schema=None) as batch_op:
        batch_op.alter_column('medium',
               existing_type=mysql.INTEGER(),
               type_=sa.String(length=22),
               existing_nullable=True)
        batch_op.create_foreign_key(None, 'detected_media', ['medium'], ['detected_medium_id'])

    with op.batch_alter_table('individuals', schema=None) as batch_op:
        batch_op.alter_column('medium',
               existing_type=mysql.INTEGER(),
               type_=sa.String(length=22),
               existing_nullable=True)
        batch_op.create_foreign_key(None, 'media', ['medium'], ['medium_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('individuals', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('medium',
               existing_type=sa.String(length=22),
               type_=mysql.INTEGER(),
               existing_nullable=True)

    with op.batch_alter_table('detected_individuals', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('medium',
               existing_type=sa.String(length=22),
               type_=mysql.INTEGER(),
               existing_nullable=True)

    # ### end Alembic commands ###
