"""uuid as medium id

Revision ID: 47897f5c147f
Revises: 2fcb0df64562
Create Date: 2023-08-02 16:32:52.124746

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '47897f5c147f'
down_revision = '2fcb0df64562'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('detected_media', schema=None) as batch_op:
        batch_op.alter_column('detected_medium_id',
               existing_type=mysql.INTEGER(),
               type_=sa.String(length=22),
               existing_nullable=False)

    with op.batch_alter_table('empty_media', schema=None) as batch_op:
        batch_op.alter_column('empty_medium_id',
               existing_type=mysql.INTEGER(),
               type_=sa.String(length=22),
               existing_nullable=False)

    with op.batch_alter_table('media', schema=None) as batch_op:
        batch_op.alter_column('medium_id',
               existing_type=mysql.INTEGER(),
               type_=sa.String(length=22),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('media', schema=None) as batch_op:
        batch_op.alter_column('medium_id',
               existing_type=sa.String(length=22),
               type_=mysql.INTEGER(),
               existing_nullable=False)

    with op.batch_alter_table('empty_media', schema=None) as batch_op:
        batch_op.alter_column('empty_medium_id',
               existing_type=sa.String(length=22),
               type_=mysql.INTEGER(),
               existing_nullable=False)

    with op.batch_alter_table('detected_media', schema=None) as batch_op:
        batch_op.alter_column('detected_medium_id',
               existing_type=sa.String(length=22),
               type_=mysql.INTEGER(),
               existing_nullable=False)

    # ### end Alembic commands ###
