"""uuid as medium id

Revision ID: 489ecfa2140c
Revises: d6ae0e0f6c8e
Create Date: 2023-08-02 16:30:06.569945

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '489ecfa2140c'
down_revision = 'd6ae0e0f6c8e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('detected_individuals', schema=None) as batch_op:
        batch_op.alter_column('medium',
               existing_type=mysql.INTEGER(),
               type_=sa.String(length=22),
               existing_nullable=True)
        batch_op.drop_constraint('detected_individuals_ibfk_1', type_='foreignkey')

    with op.batch_alter_table('detected_media', schema=None) as batch_op:
        batch_op.alter_column('detected_medium_id',
               existing_type=mysql.INTEGER(),
               type_=sa.String(length=22),
               existing_nullable=False)

    with op.batch_alter_table('empty_media', schema=None) as batch_op:
        batch_op.alter_column('empty_medium_id',
               existing_type=mysql.INTEGER(),
               type_=sa.String(length=22),
               existing_nullable=False)

    with op.batch_alter_table('individuals', schema=None) as batch_op:
        batch_op.alter_column('medium',
               existing_type=mysql.INTEGER(),
               type_=sa.String(length=22),
               existing_nullable=True)
        batch_op.drop_constraint('individuals_ibfk_1', type_='foreignkey')

    with op.batch_alter_table('media', schema=None) as batch_op:
        batch_op.alter_column('medium_id',
               existing_type=mysql.INTEGER(),
               type_=sa.String(length=22),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('media', schema=None) as batch_op:
        batch_op.alter_column('medium_id',
               existing_type=sa.String(length=22),
               type_=mysql.INTEGER(),
               existing_nullable=False)

    with op.batch_alter_table('individuals', schema=None) as batch_op:
        batch_op.create_foreign_key('individuals_ibfk_1', 'media', ['medium'], ['medium_id'])
        batch_op.alter_column('medium',
               existing_type=sa.String(length=22),
               type_=mysql.INTEGER(),
               existing_nullable=True)

    with op.batch_alter_table('empty_media', schema=None) as batch_op:
        batch_op.alter_column('empty_medium_id',
               existing_type=sa.String(length=22),
               type_=mysql.INTEGER(),
               existing_nullable=False)

    with op.batch_alter_table('detected_media', schema=None) as batch_op:
        batch_op.alter_column('detected_medium_id',
               existing_type=sa.String(length=22),
               type_=mysql.INTEGER(),
               existing_nullable=False)

    with op.batch_alter_table('detected_individuals', schema=None) as batch_op:
        batch_op.create_foreign_key('detected_individuals_ibfk_1', 'detected_media', ['medium'], ['detected_medium_id'])
        batch_op.alter_column('medium',
               existing_type=sa.String(length=22),
               type_=mysql.INTEGER(),
               existing_nullable=True)

    # ### end Alembic commands ###
