"""chinese common name longer

Revision ID: 556a84efa3a8
Revises: 85cdb7c3c1a3
Create Date: 2023-08-02 15:23:47.694845

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '556a84efa3a8'
down_revision = '85cdb7c3c1a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('species', schema=None) as batch_op:
        batch_op.alter_column('chinese_common_name',
               existing_type=mysql.VARCHAR(length=15),
               type_=sa.String(length=50),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('species', schema=None) as batch_op:
        batch_op.alter_column('chinese_common_name',
               existing_type=sa.String(length=50),
               type_=mysql.VARCHAR(length=15),
               existing_nullable=True)

    # ### end Alembic commands ###
