"""featured_by

Revision ID: 659ad308bfaa
Revises: a57e0e404177
Create Date: 2023-08-04 11:22:59.737203

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '659ad308bfaa'
down_revision = 'a57e0e404177'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('media', schema=None) as batch_op:
        batch_op.add_column(sa.Column('featured_by', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'members', ['featured_by'], ['member_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('media', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('featured_by')

    # ### end Alembic commands ###
