"""pending -> detected

Revision ID: 6e8ca68147ca
Revises: 827fbcbbdbb2
Create Date: 2023-08-02 11:38:54.336731

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e8ca68147ca'
down_revision = '827fbcbbdbb2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('detected_media',
    sa.Column('detected_medium_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('section', sa.Integer(), nullable=True),
    sa.Column('medium_datetime', sa.DateTime(), nullable=True),
    sa.Column('path', sa.String(length=255), nullable=True),
    sa.Column('reviewed', sa.Boolean(), nullable=True),
    sa.Column('empty_checker', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['empty_checker'], ['members.member_id'], ),
    sa.ForeignKeyConstraint(['section'], ['sections.section_id'], ),
    sa.PrimaryKeyConstraint('detected_medium_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('detected_media')
    # ### end Alembic commands ###
