"""first migrade

Revision ID: 726cd2b9074b
Revises: 
Create Date: 2023-07-30 21:26:40.293529

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '726cd2b9074b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('habitats',
    sa.Column('habitat_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('chinese_name', sa.String(length=10), nullable=True),
    sa.Column('english_name', sa.String(length=25), nullable=True),
    sa.PrimaryKeyConstraint('habitat_id')
    )
    op.create_table('layers',
    sa.Column('layer_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=15), nullable=True),
    sa.PrimaryKeyConstraint('layer_id')
    )
    op.create_table('mount_types',
    sa.Column('mount_type_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=15), nullable=True),
    sa.PrimaryKeyConstraint('mount_type_id')
    )
    op.create_table('positions',
    sa.Column('position_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('position_id')
    )
    op.create_table('projects',
    sa.Column('project_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=15), nullable=True),
    sa.PrimaryKeyConstraint('project_id')
    )
    op.create_table('species',
    sa.Column('taxon_order', sa.Integer(), nullable=False),
    sa.Column('scientific_name', sa.String(length=100), nullable=True),
    sa.Column('english_common_name', sa.String(length=100), nullable=True),
    sa.Column('chinese_common_name', sa.String(length=15), nullable=True),
    sa.Column('category', sa.String(length=15), nullable=True),
    sa.Column('order', sa.String(length=50), nullable=True),
    sa.Column('family_name', sa.String(length=50), nullable=True),
    sa.Column('family_latin_name', sa.String(length=50), nullable=True),
    sa.Column('taiwan_status', sa.String(length=10), nullable=True),
    sa.Column('matzu_status', sa.String(length=10), nullable=True),
    sa.Column('kinmen_status', sa.String(length=10), nullable=True),
    sa.Column('pratas_status', sa.String(length=10), nullable=True),
    sa.Column('endemism', sa.String(length=50), nullable=True),
    sa.Column('conservation_status', sa.String(length=5), nullable=True),
    sa.PrimaryKeyConstraint('taxon_order')
    )
    op.create_table('members',
    sa.Column('member_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_name', sa.String(length=20), nullable=False),
    sa.Column('first_name', sa.String(length=5), nullable=True),
    sa.Column('last_name', sa.String(length=5), nullable=True),
    sa.Column('position', sa.Integer(), nullable=True),
    sa.Column('phone_number', sa.Integer(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('is_super_user', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['position'], ['positions.position_id'], ),
    sa.PrimaryKeyConstraint('member_id'),
    sa.UniqueConstraint('phone_number'),
    sa.UniqueConstraint('user_name')
    )
    op.create_table('perch_mounts',
    sa.Column('perch_mount_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('perch_mount_name', sa.String(length=15), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('habitat', sa.Integer(), nullable=True),
    sa.Column('project', sa.Integer(), nullable=True),
    sa.Column('layer', sa.Integer(), nullable=True),
    sa.Column('terminated', sa.Boolean(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['habitat'], ['habitats.habitat_id'], ),
    sa.ForeignKeyConstraint(['layer'], ['layers.layer_id'], ),
    sa.ForeignKeyConstraint(['project'], ['projects.project_id'], ),
    sa.PrimaryKeyConstraint('perch_mount_id'),
    sa.UniqueConstraint('perch_mount_name')
    )
    op.create_table('sections',
    sa.Column('section_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('perch_mount', sa.Integer(), nullable=True),
    sa.Column('mount_type', sa.Integer(), nullable=True),
    sa.Column('camera', sa.Integer(), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('check_date', sa.Date(), nullable=True),
    sa.Column('valid', sa.Boolean(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['camera'], ['cameras.camera_id'], ),
    sa.ForeignKeyConstraint(['mount_type'], ['mount_types.mount_type_id'], ),
    sa.ForeignKeyConstraint(['perch_mount'], ['perch_mounts.perch_mount_id'], ),
    sa.PrimaryKeyConstraint('section_id')
    )
    op.create_table('empty_media',
    sa.Column('empty_medium_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('section', sa.Integer(), nullable=True),
    sa.Column('medium_datetime', sa.DateTime(), nullable=True),
    sa.Column('path', sa.String(length=255), nullable=True),
    sa.Column('checked', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['section'], ['sections.section_id'], ),
    sa.PrimaryKeyConstraint('empty_medium_id')
    )
    op.create_table('media',
    sa.Column('medium_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('section', sa.Integer(), nullable=True),
    sa.Column('medium_datetime', sa.DateTime(), nullable=True),
    sa.Column('path', sa.String(length=255), nullable=True),
    sa.Column('empty_checker', sa.Integer(), nullable=True),
    sa.Column('reviewer', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['empty_checker'], ['members.member_id'], ),
    sa.ForeignKeyConstraint(['reviewer'], ['members.member_id'], ),
    sa.ForeignKeyConstraint(['section'], ['sections.section_id'], ),
    sa.PrimaryKeyConstraint('medium_id')
    )
    op.create_table('pending_media',
    sa.Column('pending_medium_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('section', sa.Integer(), nullable=True),
    sa.Column('medium_datetime', sa.DateTime(), nullable=True),
    sa.Column('path', sa.String(length=255), nullable=True),
    sa.Column('reviewed', sa.Boolean(), nullable=True),
    sa.Column('empty_checker', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['empty_checker'], ['members.member_id'], ),
    sa.ForeignKeyConstraint(['section'], ['sections.section_id'], ),
    sa.PrimaryKeyConstraint('pending_medium_id')
    )
    op.create_table('individuals',
    sa.Column('individual_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('taxon_order_by_ai', sa.Integer(), nullable=True),
    sa.Column('taxon_order_by_human', sa.Integer(), nullable=True),
    sa.Column('medium', sa.Integer(), nullable=True),
    sa.Column('prey', sa.Boolean(), nullable=True),
    sa.Column('prey_name', sa.String(length=15), nullable=True),
    sa.Column('tagged', sa.Boolean(), nullable=True),
    sa.Column('rung_number', sa.String(length=15), nullable=True),
    sa.Column('file_type', sa.String(length=5), nullable=True),
    sa.Column('xmin', sa.Float(), nullable=True),
    sa.Column('xmax', sa.Float(), nullable=True),
    sa.Column('ymin', sa.Float(), nullable=True),
    sa.Column('ymax', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['medium'], ['media.medium_id'], ),
    sa.ForeignKeyConstraint(['taxon_order_by_ai'], ['species.taxon_order'], ),
    sa.ForeignKeyConstraint(['taxon_order_by_human'], ['species.taxon_order'], ),
    sa.PrimaryKeyConstraint('individual_id')
    )
    op.create_table('pending_individuals',
    sa.Column('pending_individual_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('taxon_order_by_ai', sa.Integer(), nullable=True),
    sa.Column('medium', sa.Integer(), nullable=True),
    sa.Column('xmin', sa.Float(), nullable=True),
    sa.Column('xmax', sa.Float(), nullable=True),
    sa.Column('ymin', sa.Float(), nullable=True),
    sa.Column('ymax', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['medium'], ['pending_media.pending_medium_id'], ),
    sa.ForeignKeyConstraint(['taxon_order_by_ai'], ['species.taxon_order'], ),
    sa.PrimaryKeyConstraint('pending_individual_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pending_individuals')
    op.drop_table('individuals')
    op.drop_table('pending_media')
    op.drop_table('media')
    op.drop_table('empty_media')
    op.drop_table('sections')
    op.drop_table('perch_mounts')
    op.drop_table('members')
    op.drop_table('species')
    op.drop_table('projects')
    op.drop_table('positions')
    op.drop_table('mount_types')
    op.drop_table('layers')
    op.drop_table('habitats')
    # ### end Alembic commands ###
