"""uuid

Revision ID: 78ebdcaf1462
Revises: 21cd7307b000
Create Date: 2023-08-02 17:55:39.181024

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78ebdcaf1462'
down_revision = '21cd7307b000'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('detected_individuals', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'detected_media', ['medium'], ['detected_medium_id'])

    with op.batch_alter_table('individuals', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'media', ['medium'], ['medium_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('individuals', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('detected_individuals', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
