"""create update info table

Revision ID: 7a1e5cf9d370
Revises: 3fc523bb75c2
Create Date: 2023-08-15 20:27:59.283690

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a1e5cf9d370'
down_revision = '3fc523bb75c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('update_info',
    sa.Column('update_info_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('file_name', sa.String(length=30), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('opened', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('update_info_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('update_info')
    # ### end Alembic commands ###
