"""super user -> super admin

Revision ID: 827fbcbbdbb2
Revises: 344c7b1e81d3
Create Date: 2023-07-30 23:54:08.159210

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '827fbcbbdbb2'
down_revision = '344c7b1e81d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('members', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_super_admin', sa.Boolean(), nullable=True))
        batch_op.drop_column('is_super_user')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('members', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_super_user', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
        batch_op.drop_column('is_super_admin')

    # ### end Alembic commands ###
