"""pending -> detected

Revision ID: 85cdb7c3c1a3
Revises: 6e8ca68147ca
Create Date: 2023-08-02 11:42:34.131571

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85cdb7c3c1a3'
down_revision = '6e8ca68147ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('detected_individuals',
    sa.Column('pending_individual_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('taxon_order_by_ai', sa.Integer(), nullable=True),
    sa.Column('medium', sa.Integer(), nullable=True),
    sa.Column('xmin', sa.Float(), nullable=True),
    sa.Column('xmax', sa.Float(), nullable=True),
    sa.Column('ymin', sa.Float(), nullable=True),
    sa.Column('ymax', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['medium'], ['detected_media.detected_medium_id'], ),
    sa.ForeignKeyConstraint(['taxon_order_by_ai'], ['species.taxon_order'], ),
    sa.PrimaryKeyConstraint('pending_individual_id')
    )
    with op.batch_alter_table('pending_individuals', schema=None) as batch_op:
        batch_op.drop_constraint('pending_individuals_ibfk_1', type_='foreignkey')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pending_individuals', schema=None) as batch_op:
        batch_op.create_foreign_key('pending_individuals_ibfk_1', 'pending_media', ['medium'], ['pending_medium_id'])

    op.drop_table('detected_individuals')
    # ### end Alembic commands ###
