"""add empty_checked in detected_media table

Revision ID: 871e1ef8a23e
Revises: c50577935b4d
Create Date: 2023-09-18 20:09:14.016703

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '871e1ef8a23e'
down_revision = 'c50577935b4d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('detected_media', schema=None) as batch_op:
        batch_op.add_column(sa.Column('empty_checked', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('detected_media', schema=None) as batch_op:
        batch_op.drop_column('empty_checked')

    # ### end Alembic commands ###
