"""s3_file_path field of media

Revision ID: 8cc2bb1caece
Revises: 93f7b54c2c5d
Create Date: 2026-02-28 22:10:32.705254

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "8cc2bb1caece"
down_revision = "93f7b54c2c5d"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table("media", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("s3_file_name", sa.String(length=255), nullable=True)
        )

    with op.batch_alter_table("members", schema=None) as batch_op:
        batch_op.alter_column(
            "user_name", existing_type=sa.VARCHAR(length=50), nullable=True
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table("members", schema=None) as batch_op:
        batch_op.alter_column(
            "user_name", existing_type=sa.VARCHAR(length=50), nullable=False
        )

    with op.batch_alter_table("media", schema=None) as batch_op:
        batch_op.drop_column("s3_file_name")
    # ### end Alembic commands ###
