"""uuid

Revision ID: 8cce77806c68
Revises: a2aa4371b66c
Create Date: 2023-08-02 17:20:25.955614

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql
import src.model

# revision identifiers, used by Alembic.
revision = "8cce77806c68"
down_revision = "a2aa4371b66c"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("detected_media", schema=None) as batch_op:
        batch_op.alter_column(
            "detected_medium_id",
            existing_type=mysql.VARCHAR(length=22),
            type_=src.model.GUID(),
            existing_nullable=False,
        )

    with op.batch_alter_table("empty_media", schema=None) as batch_op:
        batch_op.alter_column(
            "empty_medium_id",
            existing_type=mysql.VARCHAR(length=22),
            type_=src.model.GUID(),
            existing_nullable=False,
        )

    with op.batch_alter_table("media", schema=None) as batch_op:
        batch_op.alter_column(
            "medium_id",
            existing_type=mysql.VARCHAR(length=22),
            type_=src.model.GUID(),
            existing_nullable=False,
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("media", schema=None) as batch_op:
        batch_op.alter_column(
            "medium_id",
            existing_type=src.model.GUID(),
            type_=mysql.VARCHAR(length=22),
            existing_nullable=False,
        )

    with op.batch_alter_table("empty_media", schema=None) as batch_op:
        batch_op.alter_column(
            "empty_medium_id",
            existing_type=src.model.GUID(),
            type_=mysql.VARCHAR(length=22),
            existing_nullable=False,
        )

    with op.batch_alter_table("detected_media", schema=None) as batch_op:
        batch_op.alter_column(
            "detected_medium_id",
            existing_type=src.model.GUID(),
            type_=mysql.VARCHAR(length=22),
            existing_nullable=False,
        )

    # ### end Alembic commands ###
