"""uuid

Revision ID: 8d5693c41ba7
Revises: 2dfc7c4b66ea
Create Date: 2023-08-02 17:54:29.271316

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d5693c41ba7'
down_revision = '2dfc7c4b66ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('detected_individuals', schema=None) as batch_op:
        batch_op.drop_constraint('detected_individuals_ibfk_3', type_='foreignkey')

    with op.batch_alter_table('individuals', schema=None) as batch_op:
        batch_op.drop_constraint('individuals_ibfk_4', type_='foreignkey')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('individuals', schema=None) as batch_op:
        batch_op.create_foreign_key('individuals_ibfk_4', 'media', ['medium'], ['medium_id'])

    with op.batch_alter_table('detected_individuals', schema=None) as batch_op:
        batch_op.create_foreign_key('detected_individuals_ibfk_3', 'detected_media', ['medium'], ['detected_medium_id'])

    # ### end Alembic commands ###
