"""species codes table

Revision ID: 968f08666507
Revises: b6ed60e93041
Create Date: 2023-08-07 16:29:27.883284

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '968f08666507'
down_revision = 'b6ed60e93041'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('species_codes',
    sa.Column('taxon_order', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.ForeignKeyConstraint(['taxon_order'], ['species.taxon_order'], ),
    sa.PrimaryKeyConstraint('taxon_order', 'code')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('species_codes')
    # ### end Alembic commands ###
