"""update message to text

Revision ID: 9841eb615eaa
Revises: c6c1d1c5e4df
Create Date: 2023-08-16 16:15:52.799109

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9841eb615eaa'
down_revision = 'c6c1d1c5e4df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('update_info', schema=None) as batch_op:
        batch_op.alter_column('message',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=30),
               type_=sa.Text(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('update_info', schema=None) as batch_op:
        batch_op.alter_column('message',
               existing_type=sa.Text(),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=30),
               existing_nullable=True)

    # ### end Alembic commands ###
