"""uuid

Revision ID: a2aa4371b66c
Revises: 3fea6b016d17
Create Date: 2023-08-02 17:18:34.436188

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a2aa4371b66c'
down_revision = '3fea6b016d17'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('detected_individuals', schema=None) as batch_op:
        batch_op.drop_constraint('detected_individuals_ibfk_3', type_='foreignkey')

    with op.batch_alter_table('individuals', schema=None) as batch_op:
        batch_op.drop_constraint('individuals_ibfk_4', type_='foreignkey')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('individuals', schema=None) as batch_op:
        batch_op.create_foreign_key('individuals_ibfk_4', 'media', ['medium'], ['medium_id'])

    with op.batch_alter_table('detected_individuals', schema=None) as batch_op:
        batch_op.create_foreign_key('detected_individuals_ibfk_3', 'detected_media', ['medium'], ['detected_medium_id'])

    # ### end Alembic commands ###
