"""second

Revision ID: a6773bdef653
Revises: 726cd2b9074b
Create Date: 2023-07-30 21:40:01.000758

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a6773bdef653'
down_revision = '726cd2b9074b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('events',
    sa.Column('event_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('chinese_name', sa.String(length=15), nullable=True),
    sa.Column('english_name', sa.String(length=15), nullable=True),
    sa.PrimaryKeyConstraint('event_id')
    )
    op.create_table('section_operaters',
    sa.Column('section', sa.Integer(), nullable=False),
    sa.Column('operator', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['operator'], ['members.member_id'], ),
    sa.ForeignKeyConstraint(['section'], ['sections.section_id'], ),
    sa.PrimaryKeyConstraint('section', 'operator')
    )
    with op.batch_alter_table('media', schema=None) as batch_op:
        batch_op.add_column(sa.Column('event', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'events', ['event'], ['event_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('media', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('event')

    op.drop_table('section_operaters')
    op.drop_table('events')
    # ### end Alembic commands ###
