"""new version clear versions

Revision ID: a78ac5958ed9
Revises: 
Create Date: 2024-02-11 14:46:48.170420

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a78ac5958ed9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('actions',
    sa.Column('action_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=15), nullable=True),
    sa.PrimaryKeyConstraint('action_id')
    )
    op.create_table('behaviors',
    sa.Column('behavior_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('chinese_name', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('behavior_id')
    )
    op.create_table('cameras',
    sa.Column('camera_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('model_name', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('camera_id')
    )
    op.create_table('events',
    sa.Column('event_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('chinese_name', sa.String(length=15), nullable=True),
    sa.Column('english_name', sa.String(length=15), nullable=True),
    sa.PrimaryKeyConstraint('event_id')
    )
    op.create_table('habitats',
    sa.Column('habitat_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('chinese_name', sa.String(length=10), nullable=True),
    sa.Column('english_name', sa.String(length=25), nullable=True),
    sa.PrimaryKeyConstraint('habitat_id')
    )
    op.create_table('layers',
    sa.Column('layer_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=15), nullable=True),
    sa.PrimaryKeyConstraint('layer_id')
    )
    op.create_table('mount_types',
    sa.Column('mount_type_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=15), nullable=True),
    sa.PrimaryKeyConstraint('mount_type_id')
    )
    op.create_table('positions',
    sa.Column('position_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('position_id')
    )
    op.create_table('projects',
    sa.Column('project_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=15), nullable=True),
    sa.PrimaryKeyConstraint('project_id')
    )
    op.create_table('species',
    sa.Column('taxon_order', sa.Integer(), nullable=False),
    sa.Column('scientific_name', sa.String(length=100), nullable=True),
    sa.Column('english_common_name', sa.String(length=100), nullable=True),
    sa.Column('chinese_common_name', sa.String(length=50), nullable=True),
    sa.Column('category', sa.String(length=15), nullable=True),
    sa.Column('order', sa.String(length=50), nullable=True),
    sa.Column('family_name', sa.String(length=50), nullable=True),
    sa.Column('family_latin_name', sa.String(length=50), nullable=True),
    sa.Column('taiwan_status', sa.String(length=50), nullable=True),
    sa.Column('matzu_status', sa.String(length=50), nullable=True),
    sa.Column('kinmen_status', sa.String(length=50), nullable=True),
    sa.Column('pratas_status', sa.String(length=50), nullable=True),
    sa.Column('endemism', sa.String(length=50), nullable=True),
    sa.Column('conservation_status', sa.String(length=5), nullable=True),
    sa.Column('usage_count', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('taxon_order')
    )
    op.create_table('update_info',
    sa.Column('update_info_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('create_date', sa.Date(), nullable=True),
    sa.Column('checked', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('update_info_id')
    )
    op.create_table('members',
    sa.Column('member_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_name', sa.String(length=20), nullable=False),
    sa.Column('first_name', sa.String(length=5), nullable=True),
    sa.Column('last_name', sa.String(length=5), nullable=True),
    sa.Column('position', sa.Integer(), nullable=True),
    sa.Column('phone_number', sa.String(length=10), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('is_super_admin', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['position'], ['positions.position_id'], ),
    sa.PrimaryKeyConstraint('member_id'),
    sa.UniqueConstraint('phone_number'),
    sa.UniqueConstraint('user_name')
    )
    op.create_table('species_codes',
    sa.Column('taxon_order', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.ForeignKeyConstraint(['taxon_order'], ['species.taxon_order'], ),
    sa.PrimaryKeyConstraint('taxon_order', 'code')
    )
    op.create_table('contributions',
    sa.Column('contribution_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('contributor', sa.Integer(), nullable=True),
    sa.Column('num_files', sa.Integer(), nullable=False),
    sa.Column('action', sa.Integer(), nullable=True),
    sa.Column('time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['action'], ['actions.action_id'], ),
    sa.ForeignKeyConstraint(['contributor'], ['members.member_id'], ),
    sa.PrimaryKeyConstraint('contribution_id')
    )
    op.create_table('perch_mounts',
    sa.Column('perch_mount_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('perch_mount_name', sa.String(length=15), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('habitat', sa.Integer(), nullable=False),
    sa.Column('project', sa.Integer(), nullable=False),
    sa.Column('layer', sa.Integer(), nullable=True),
    sa.Column('terminated', sa.Boolean(), nullable=True),
    sa.Column('latest_note', sa.Text(), nullable=True),
    sa.Column('is_priority', sa.Boolean(), nullable=True),
    sa.Column('claim_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['claim_by'], ['members.member_id'], ),
    sa.ForeignKeyConstraint(['habitat'], ['habitats.habitat_id'], ),
    sa.ForeignKeyConstraint(['layer'], ['layers.layer_id'], ),
    sa.ForeignKeyConstraint(['project'], ['projects.project_id'], ),
    sa.PrimaryKeyConstraint('perch_mount_id'),
    sa.UniqueConstraint('perch_mount_name')
    )
    op.create_table('sections',
    sa.Column('section_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('perch_mount', sa.Integer(), nullable=True),
    sa.Column('mount_type', sa.Integer(), nullable=True),
    sa.Column('camera', sa.Integer(), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('check_date', sa.Date(), nullable=True),
    sa.Column('valid', sa.Boolean(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['camera'], ['cameras.camera_id'], ),
    sa.ForeignKeyConstraint(['mount_type'], ['mount_types.mount_type_id'], ),
    sa.ForeignKeyConstraint(['perch_mount'], ['perch_mounts.perch_mount_id'], ),
    sa.PrimaryKeyConstraint('section_id')
    )
    op.create_table('detected_media',
    sa.Column('detected_medium_id', sa.String(length=22), nullable=False),
    sa.Column('section', sa.Integer(), nullable=True),
    sa.Column('medium_datetime', sa.DateTime(), nullable=True),
    sa.Column('path', sa.String(length=255), nullable=True),
    sa.Column('reviewed', sa.Boolean(), nullable=True),
    sa.Column('empty_checker', sa.Integer(), nullable=True),
    sa.Column('empty_checked', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['empty_checker'], ['members.member_id'], ),
    sa.ForeignKeyConstraint(['section'], ['sections.section_id'], ),
    sa.PrimaryKeyConstraint('detected_medium_id')
    )
    op.create_table('empty_media',
    sa.Column('empty_medium_id', sa.String(length=22), nullable=False),
    sa.Column('section', sa.Integer(), nullable=True),
    sa.Column('medium_datetime', sa.DateTime(), nullable=True),
    sa.Column('path', sa.String(length=255), nullable=True),
    sa.Column('checked', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['section'], ['sections.section_id'], ),
    sa.PrimaryKeyConstraint('empty_medium_id')
    )
    op.create_table('media',
    sa.Column('medium_id', sa.String(length=22), nullable=False),
    sa.Column('section', sa.Integer(), nullable=True),
    sa.Column('medium_datetime', sa.DateTime(), nullable=True),
    sa.Column('path', sa.String(length=255), nullable=True),
    sa.Column('empty_checker', sa.Integer(), nullable=True),
    sa.Column('reviewer', sa.Integer(), nullable=True),
    sa.Column('event', sa.Integer(), nullable=True),
    sa.Column('featured', sa.Boolean(), nullable=True),
    sa.Column('featured_by', sa.Integer(), nullable=True),
    sa.Column('featured_title', sa.String(length=100), nullable=True),
    sa.Column('featured_behavior', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['empty_checker'], ['members.member_id'], ),
    sa.ForeignKeyConstraint(['event'], ['events.event_id'], ),
    sa.ForeignKeyConstraint(['featured_behavior'], ['behaviors.behavior_id'], ),
    sa.ForeignKeyConstraint(['featured_by'], ['members.member_id'], ),
    sa.ForeignKeyConstraint(['reviewer'], ['members.member_id'], ),
    sa.ForeignKeyConstraint(['section'], ['sections.section_id'], ),
    sa.PrimaryKeyConstraint('medium_id')
    )
    op.create_table('schedule_detect',
    sa.Column('schedule_detect_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('num_files', sa.Integer(), nullable=True),
    sa.Column('detect_datetime', sa.DateTime(), nullable=True),
    sa.Column('section', sa.Integer(), nullable=True),
    sa.Column('is_image', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['section'], ['sections.section_id'], ),
    sa.PrimaryKeyConstraint('schedule_detect_id')
    )
    op.create_table('section_operaters',
    sa.Column('section', sa.Integer(), nullable=False),
    sa.Column('operator', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['operator'], ['members.member_id'], ),
    sa.ForeignKeyConstraint(['section'], ['sections.section_id'], ),
    sa.PrimaryKeyConstraint('section', 'operator')
    )
    op.create_table('detected_individuals',
    sa.Column('pending_individual_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('taxon_order_by_ai', sa.Integer(), nullable=True),
    sa.Column('medium', sa.String(length=22), nullable=True),
    sa.Column('xmin', sa.Float(), nullable=True),
    sa.Column('xmax', sa.Float(), nullable=True),
    sa.Column('ymin', sa.Float(), nullable=True),
    sa.Column('ymax', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['medium'], ['detected_media.detected_medium_id'], ),
    sa.ForeignKeyConstraint(['taxon_order_by_ai'], ['species.taxon_order'], ),
    sa.PrimaryKeyConstraint('pending_individual_id')
    )
    op.create_table('individuals',
    sa.Column('individual_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('taxon_order_by_ai', sa.Integer(), nullable=True),
    sa.Column('taxon_order_by_human', sa.Integer(), nullable=True),
    sa.Column('medium', sa.String(length=22), nullable=True),
    sa.Column('prey', sa.Boolean(), nullable=True),
    sa.Column('prey_name', sa.String(length=15), nullable=True),
    sa.Column('tagged', sa.Boolean(), nullable=True),
    sa.Column('ring_number', sa.String(length=15), nullable=True),
    sa.Column('file_type', sa.String(length=5), nullable=True),
    sa.Column('xmin', sa.Float(), nullable=True),
    sa.Column('xmax', sa.Float(), nullable=True),
    sa.Column('ymin', sa.Float(), nullable=True),
    sa.Column('ymax', sa.Float(), nullable=True),
    sa.Column('prey_identify_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['medium'], ['media.medium_id'], ),
    sa.ForeignKeyConstraint(['prey_identify_by'], ['members.member_id'], ),
    sa.ForeignKeyConstraint(['taxon_order_by_ai'], ['species.taxon_order'], ),
    sa.ForeignKeyConstraint(['taxon_order_by_human'], ['species.taxon_order'], ),
    sa.PrimaryKeyConstraint('individual_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('individuals')
    op.drop_table('detected_individuals')
    op.drop_table('section_operaters')
    op.drop_table('schedule_detect')
    op.drop_table('media')
    op.drop_table('empty_media')
    op.drop_table('detected_media')
    op.drop_table('sections')
    op.drop_table('perch_mounts')
    op.drop_table('contributions')
    op.drop_table('species_codes')
    op.drop_table('members')
    op.drop_table('update_info')
    op.drop_table('species')
    op.drop_table('projects')
    op.drop_table('positions')
    op.drop_table('mount_types')
    op.drop_table('layers')
    op.drop_table('habitats')
    op.drop_table('events')
    op.drop_table('cameras')
    op.drop_table('behaviors')
    op.drop_table('actions')
    # ### end Alembic commands ###
