"""schedule datect perch mount -> section

Revision ID: b5b5da8ce964
Revises: 37d34745cf11
Create Date: 2023-08-23 00:19:22.578141

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b5b5da8ce964'
down_revision = '37d34745cf11'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('schedule_detect', schema=None) as batch_op:
        batch_op.add_column(sa.Column('section', sa.Integer(), nullable=True))
        batch_op.drop_constraint('schedule_detect_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'sections', ['section'], ['section_id'])
        batch_op.drop_column('perch_mount')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('schedule_detect', schema=None) as batch_op:
        batch_op.add_column(sa.Column('perch_mount', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('schedule_detect_ibfk_1', 'perch_mounts', ['perch_mount'], ['perch_mount_id'])
        batch_op.drop_column('section')

    # ### end Alembic commands ###
