"""detail filename col

Revision ID: c03a8aa7bded
Revises: 7a1e5cf9d370
Create Date: 2023-08-15 22:27:15.448796

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c03a8aa7bded'
down_revision = '7a1e5cf9d370'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('update_info', schema=None) as batch_op:
        batch_op.add_column(sa.Column('detail_file_name', sa.String(length=30), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('update_info', schema=None) as batch_op:
        batch_op.drop_column('detail_file_name')

    # ### end Alembic commands ###
