"""update info in data not md file

Revision ID: c6c1d1c5e4df
Revises: e164ba7df4cc
Create Date: 2023-08-16 08:36:43.511521

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c6c1d1c5e4df'
down_revision = 'e164ba7df4cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('update_info', schema=None) as batch_op:
        batch_op.add_column(sa.Column('message', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('detail', sa.Text(), nullable=True))
        batch_op.drop_column('detail_file_name')
        batch_op.drop_column('message_file_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('update_info', schema=None) as batch_op:
        batch_op.add_column(sa.Column('message_file_name', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=30), nullable=True))
        batch_op.add_column(sa.Column('detail_file_name', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=30), nullable=True))
        batch_op.drop_column('detail')
        batch_op.drop_column('message')

    # ### end Alembic commands ###
