"""featured_discription -> featured_title

Revision ID: db723917e205
Revises: 3571940cbe27
Create Date: 2023-08-07 21:09:49.437271

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'db723917e205'
down_revision = '3571940cbe27'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('media', schema=None) as batch_op:
        batch_op.add_column(sa.Column('featured_title', sa.String(length=100), nullable=True))
        batch_op.drop_column('featured_discription')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('media', schema=None) as batch_op:
        batch_op.add_column(sa.Column('featured_discription', mysql.VARCHAR(length=100), nullable=True))
        batch_op.drop_column('featured_title')

    # ### end Alembic commands ###
