"""uuid

Revision ID: e1794de33ae4
Revises: 8cce77806c68
Create Date: 2023-08-02 17:33:26.468440

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e1794de33ae4'
down_revision = '8cce77806c68'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('detected_individuals', schema=None) as batch_op:
        batch_op.alter_column('medium',
               existing_type=mysql.VARCHAR(length=22),
               type_=sa.String(length=32),
               existing_nullable=True)
        batch_op.create_foreign_key(None, 'detected_media', ['medium'], ['detected_medium_id'])

    with op.batch_alter_table('individuals', schema=None) as batch_op:
        batch_op.alter_column('medium',
               existing_type=mysql.VARCHAR(length=22),
               type_=sa.String(length=32),
               existing_nullable=True)
        batch_op.create_foreign_key(None, 'media', ['medium'], ['medium_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('individuals', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('medium',
               existing_type=sa.String(length=32),
               type_=mysql.VARCHAR(length=22),
               existing_nullable=True)

    with op.batch_alter_table('detected_individuals', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('medium',
               existing_type=sa.String(length=32),
               type_=mysql.VARCHAR(length=22),
               existing_nullable=True)

    # ### end Alembic commands ###
