"""uuid

Revision ID: f16ff60e8033
Revises: d50c106b8bc5
Create Date: 2023-08-02 17:53:53.291040

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f16ff60e8033'
down_revision = 'd50c106b8bc5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('detected_individuals', schema=None) as batch_op:
        batch_op.alter_column('medium',
               existing_type=mysql.VARCHAR(length=32),
               type_=sa.String(length=22),
               existing_nullable=True)
        batch_op.drop_constraint('detected_individuals_ibfk_3', type_='foreignkey')

    with op.batch_alter_table('detected_media', schema=None) as batch_op:
        batch_op.alter_column('detected_medium_id',
               existing_type=mysql.VARCHAR(length=32),
               type_=sa.String(length=22),
               existing_nullable=False)

    with op.batch_alter_table('empty_media', schema=None) as batch_op:
        batch_op.alter_column('empty_medium_id',
               existing_type=mysql.VARCHAR(length=32),
               type_=sa.String(length=22),
               existing_nullable=False)

    with op.batch_alter_table('individuals', schema=None) as batch_op:
        batch_op.alter_column('medium',
               existing_type=mysql.VARCHAR(length=32),
               type_=sa.String(length=22),
               existing_nullable=True)
        batch_op.drop_constraint('individuals_ibfk_4', type_='foreignkey')

    with op.batch_alter_table('media', schema=None) as batch_op:
        batch_op.alter_column('medium_id',
               existing_type=mysql.VARCHAR(length=32),
               type_=sa.String(length=22),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('media', schema=None) as batch_op:
        batch_op.alter_column('medium_id',
               existing_type=sa.String(length=22),
               type_=mysql.VARCHAR(length=32),
               existing_nullable=False)

    with op.batch_alter_table('individuals', schema=None) as batch_op:
        batch_op.create_foreign_key('individuals_ibfk_4', 'media', ['medium'], ['medium_id'])
        batch_op.alter_column('medium',
               existing_type=sa.String(length=22),
               type_=mysql.VARCHAR(length=32),
               existing_nullable=True)

    with op.batch_alter_table('empty_media', schema=None) as batch_op:
        batch_op.alter_column('empty_medium_id',
               existing_type=sa.String(length=22),
               type_=mysql.VARCHAR(length=32),
               existing_nullable=False)

    with op.batch_alter_table('detected_media', schema=None) as batch_op:
        batch_op.alter_column('detected_medium_id',
               existing_type=sa.String(length=22),
               type_=mysql.VARCHAR(length=32),
               existing_nullable=False)

    with op.batch_alter_table('detected_individuals', schema=None) as batch_op:
        batch_op.create_foreign_key('detected_individuals_ibfk_3', 'detected_media', ['medium'], ['detected_medium_id'])
        batch_op.alter_column('medium',
               existing_type=sa.String(length=22),
               type_=mysql.VARCHAR(length=32),
               existing_nullable=True)

    # ### end Alembic commands ###
