"""date to datetime

Revision ID: fdb7021a0337
Revises: 2efc493e2a04
Create Date: 2023-08-22 23:49:23.885599

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fdb7021a0337'
down_revision = '2efc493e2a04'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('schedule_detect', schema=None) as batch_op:
        batch_op.alter_column('detect_datetime',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('schedule_detect', schema=None) as batch_op:
        batch_op.alter_column('detect_datetime',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=True)

    # ### end Alembic commands ###
